import {
    generatePlaceValue5Digit,
    generateAddition4Digit,
    generatePlaceValue5DigitVisual,
    generateAddition4DigitAppliactionLevel,
    generateExpandedForm,
    generateSubtraction4Digit,
    generateSubtraction4DigitAppliactionLevel,
    generateMultiplication,
    generateMultiplicationApplicationLevel,
    generateDivision,
    generateDivisionApplicationLevel,
    generateLCM,
    generateEstimation,
    generateProperImproperFractions,
    generateMixedUnitFractions,
    generateFractionOperations,
    generateAngles,
    generateTriangles,
    generateAreaShape,
    generatePerimeterShape,
    generateMeasurementConversion,
    generateBarGraph,
    generateSimpleGrade4Pattern,
    generateMeasurementConversionApplicationLevel,
    generate3DShapeIdentification,
    generateFVETable,
} from './grade4Generators.mjs';

const generate = (generator, count = 10) => {
    return Array.from({ length: count }, () => generator());
};

const Grade4Questions = {
    q1: generate(generatePlaceValue5Digit),
    q2: generate(generatePlaceValue5DigitVisual),
    q3: generate(generateExpandedForm),
    q4: generate(generateAddition4Digit),
    q5: generate(generateAddition4DigitAppliactionLevel),
    q6: generate(generateSubtraction4Digit),
    q7: generate(generateSubtraction4DigitAppliactionLevel),
    q8: generate(generateMultiplication),
    q9: generate(generateMultiplicationApplicationLevel),
    q10: generate(generateDivision),
    q11: generate(generateDivisionApplicationLevel),
    q12: generate(generateLCM),
    q13: generate(generateEstimation),
    // q12: generate(generateEstimation),
    q14: generate(generateProperImproperFractions),
    q15: generate(generateMixedUnitFractions),
    q16: generate(generateFractionOperations),
    q17: generate(generateAngles),
    // q17: generate(generateAngles),
    q18: generate(generateTriangles),
    // q19: generate(generateTriangles),
    q19: generate(generate3DShapeIdentification),
    q20: generate(generateFVETable),
    q21: generate(generateAreaShape),
    // q22: generate(generatePerimeterShape),
    q22: generate(generateMeasurementConversion),
    q23: generate(generateMeasurementConversionApplicationLevel),
    q24: generate(generateBarGraph),
    q25: generate(generateSimpleGrade4Pattern),

    // q26: generate(generateSimpleGrade4Pattern),
    // Fill remaining slots
    // q15: generate(generatePlaceValue5Digit),
    // q16: generate(generateAddition4Digit),
    // q17: generate(generateSubtraction4Digit),
    // q18: generate(generateMultiplication),
    // q19: generate(generateDivision),
    // q20: generate(generateEstimation),
    // q21: generate(generateFractionTypes),
    // q22: generate(generateFractionOperations),
    // q23: generate(generateAngles),
    // q24: generate(generateTriangles),
    // q25: generate(generateAreaPerimeter),
    // q26: generate(generateTimeConversion),
    // q27: generate(generateBarGraph),
    // q28: generate(generateSimpleGrade4Pattern),
    // q29: generate(generatePlaceValue5Digit),
    // q30: generate(generateAddition4Digit)
};


export const Grade4GeneratorMap = {
    "Number Sense / Place Value": () => Math.random() > 0.5 ? generatePlaceValue5Digit() : generatePlaceValue5DigitVisual(),
    "Number Sense / Expanded Form": generateExpandedForm,
    "Addition / With Carry": () => Math.random() > 0.5 ? generateAddition4Digit() : generateAddition4DigitAppliactionLevel(),
    "Subtraction / With Borrow": () => Math.random() > 0.5 ? generateSubtraction4Digit() : generateSubtraction4DigitAppliactionLevel(),
    "Number Sense / Multiplication": generateMultiplication,
    "Multiplication / 2-digit × 2-digit": generateMultiplicationApplicationLevel,
    "Number Sense / Division": generateDivision,
    "Division / 3-digit ÷ 1-digit": generateDivisionApplicationLevel,
    "Number Sense / Estimation": generateEstimation,
    "Number Sense / LCM": generateLCM,
    "Fractions / Types": () => Math.random() > 0.5 ? generateProperImproperFractions() : generateMixedUnitFractions(),
    "Fractions / Operations": generateFractionOperations,
    "Geometry / Angles": generateAngles,
    "Geometry / Triangles": generateTriangles,
    "Measurement / Area": generateAreaShape,
    "Measurement / Perimeter": generatePerimeterShape,
    "Measurement / Conversion": () => Math.random() > 0.5 ? generateMeasurementConversion() : generateMeasurementConversionApplicationLevel(),
    "Data Handling / Bar Graph": generateBarGraph,
    "Patterns / Number Patterns": generateSimpleGrade4Pattern,
    "Geometry / 3D Shapes": generate3DShapeIdentification,
    "Geometry / 3D Shapes - FVE": generateFVETable
};

export default Grade4Questions;

